searchPath : /liquibase/changelog
changeLogFile : changelogs/db.changelog-master.yml

driver   : org.postgresql.Driver
url      : ${database.url}
username : ${database.username}
password : ${database.password}

verbose : true