dataSourceClassName     = org.postgresql.ds.PGSimpleDataSource
dataSource.url          = ${database.url}
dataSource.user         = ${database.username}
dataSource.password     = ${database.password}

autoCommit      = true
maximumPoolSize = 8
